import type { Metadata } from 'next';
import './globals.css';
// Tanstack Query required component to be a client component so a ClientProviders was created
import ClientProviders from '@/src/components/ClientProviders';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
