# Generated by Django 5.2 on 2025-05-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='location',
            new_name='site',
        ),
    ]
