# Generated by Django 5.2 on 2025-05-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_location_items_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='accepted_by_name',
            new_name='accepted_by_email',
        ),
    ]
