# Generated by Django 5.2 on 2025-05-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_rename_accepted_by_name_items_accepted_by_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_returned_by_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
