# Generated by Django 5.2 on 2025-05-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_location_items_site'),
        ('locations', '0002_alter_building_name_alter_department_level_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Site',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='location',
            new_name='site',
        ),
    ]
