# Generated by Django 5.2 on 2025-05-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_rename_location_site_rename_location_building_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='number',
            new_name='name',
        ),
    ]
